[versions]
assertj-core = "3.27.7"
commons-text = "1.15.0"
flying-saucer-pdf = "10.0.6"
groovy = "5.+"
jbake = "5.5.0"
jsoup = "1.22.1"
junit-jupiter = "6.0.3"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
flying-saucer-pdf = { module = "org.xhtmlrenderer:flying-saucer-pdf", version.ref = "flying-saucer-pdf" }
groovy-all = { module = "org.apache.groovy:groovy-all", version.ref = "groovy" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
groovy = { id = "groovy" }
jbake = { id = "org.jbake.site", version.ref = "jbake" }